apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - planner.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: ghcr.io/ishioni/branch-planner
    newName: ghcr.io/ishioni/branch-planner
    newTag: v0.16.5-ishioni.1
